name: Deploy to Private Docker Registry

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update index.html
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          sed -i "s/{{TIMESTAMP}}/$TIMESTAMP/g" index.html
          git config --global user.name "mk8scloud-aws"
          git config --global user.email "mk8scloud@gmail.com"
          git add index.html
          # Only commit and push if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update index.html with timestamp"
            git push
          fi

      - name: Log in to Private Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login http://192.168.0.60:8083 -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t 192.168.0.60:8083/my-repo:latest .
          docker push 192.168.0.60:8083/my-repo:latest